### ISSUE TITLE
No inline js for no reason

### ISSUE THREAD

**Issue by BojidarStanchev** [todorakisa/Diploma#10]
https://github.com/todorakisa/Diploma/blob/2f66a14d9aebe18ca4a600bdeffcbb281fabf13c/BoardFind/templates/home/EventsAndPeople.html.twig#L48

All custom js should be in a folder  (and split into subfolders if too many files) 
Inline js is allowed only in one-liner situations when you are in a hurry and you write a todo comment like "TODO: Move in its own file" - this allows people to see you're reasonable and did it in a rush.

**Comment by todorakisa** [comment]
i corrected my code
