### ISSUE TITLE
This method should not be named "success", it gives no info what is going on. Do you even need it?

### ISSUE THREAD

**Issue by BojidarStanchev** [todorakisa/Diploma#6]
https://github.com/todorakisa/Diploma/blob/2f66a14d9aebe18ca4a600bdeffcbb281fabf13c/BoardFind/src/Controller/UserController.php#L41

**Comment by BojidarStanchev** [comment]
I imagine this should be a "flash message" for success/error. (google flash message and click on images if you don't know what that is). Basically, it's a small colored strip usually on the top of the website pushing the content down and it contains important information (eg. "changes saved", "error: operation not complete", etc.) 

Right now you use the backend to render this whole thing for you. I suggest you just add it to your base HTML twig and hide it. Then whenever you need it, just show it from the javascript with some text. This way you don't make useless requests and fill your code with functions like the one above. The price is having a few bytes overhead on every page because your HTML would be a few lines longer, but that is negligible

**Comment by todorakisa** [comment]
Solved
